### ISSUE TITLE
Can't build project anymore

### ISSUE THREAD

**Issue by MrCreeperkopf** [jenkinsci/gitlab-hook-plugin#48]
ERROR: private method `warn' called for #<Jenkins::Plugin::OpaqueJavaObject:0x63a0991b> (NoMethodError)
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/gitlab_notifier.rb:24:in `prebuild'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:8:in `prebuild'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:7:in `prebuild'

Jenkins v2.91

**Comment by javiplx** [comment]
Have you updated Jenkins or any plugin since the previously working execution?

**Comment by MrCreeperkopf** [comment]
No. Strangely other projects are working fine.

**Comment by javiplx** [comment]
As it apparently happens on notifier, check the permission level of Jenkins user in that particular project respect to the other ones.
As a test, you could remove the notification action, which anyway does not work smoothly in recent gitlab releases

**Comment by MrCreeperkopf** [comment]
Nope doesn't help. Still the same error.
