### ISSUE TITLE
ERROR: load error: openssl -- java.lang.VerifyError

### ISSUE THREAD

**Issue by szpak** [jenkinsci/gitlab-hook-plugin#56]
The plugin seems to cause runtime errors on a job execution:

```
ERROR: load error: openssl -- java.lang.VerifyError: (class: org/jruby/ext/openssl/X509Cert, method: sign signature: (Lorg/jruby/runtime/ThreadContext;Lorg/jruby/runtime/builtin/IRubyObject;Lorg/jruby/runtime/builtin/IRubyObject;)Lorg/jruby/runtime/builtin/IRubyObject;) Incompatible argument to function (LoadError)
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/lib/gitlab/client.rb:116:in `do_request'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/lib/gitlab/client.rb:87:in `repo_id'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/lib/gitlab/client.rb:19:in `name='
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/models/gitlab_notifier.rb:27:in `prebuild'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:8:in `prebuild'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:22:in `boolean_result'
/var/lib/jenkins/plugins/gitlab-hook/WEB-INF/classes/vendor/gems/gems/jenkins-plugin-runtime-0.2.3/lib/jenkins/tasks/build_step_proxy.rb:7:in `prebuild'
```
gitlab-hook 1.4.2, Jenkins 2.60, Java 1.8.0_131 (HotSpot).

**Comment by ghost** [comment]
Same case
