### ISSUE TITLE
ruby-runtime plugin issue

### ISSUE THREAD

**Issue by venkatasykam** [jenkinsci/gitlab-hook-plugin#60]
Hi Team,

I am using openjdk 11 on my redhat linux machine. My jenkins upgraded from 2.150.1 to 2.204.2 version. After the upgrade, gitlab-hook-plugin is not loading due to ruby-runtime plugin issue. When I am trying to install ruby-runtime plugin 0.12 I am facing the below error.

java.lang.RuntimeExceptipn: unsupported Java version 11
at org.jruby.RubyInstacneConfig.initiGlobalJavaVersion(RubyInstacneConfig.java:1674)
at org.jruby.RubyInstacneConfig.<clinit>(RubyInstacneConfig.java:1387)

Caused: java.lang.ExceptionInInitializerError

Thanks,
Venkat

**Comment by smily75** [comment]
Hi Team,

I have the same problem. Is it possible that you use an other ruby plugin? The ruby-rumtime plugin is for 2016 and will not be updated. 

Thanks
Sandra

**Comment by aircon-chen** [comment]
I have the same problem.  Buy my solution is to downgrade java version to java 8 , then it works well.
